### ISSUE TITLE
Get body from url

### ISSUE THREAD

**Issue by KANekT** [Cap-go/capacitor-inappbrowser#1]
You planned executeScript in this Plagin or Get html / text from page ?

**Comment by riderx** [comment]
Nothing like that is plan for now, my need are meet with current feature. If you are interested in this feature I could develop it, if you are open to sponsor my work:
https://github.com/sponsors/riderx

**Comment by KANekT** [comment]
This functionality is not critical for me

I will continue using the cordova plugin
