### ISSUE TITLE
iOS vs Android vs Web (if possible?)

### ISSUE THREAD

**Issue by gerhardcit** [Cap-go/capacitor-inappbrowser#104]
Is this plugin designed for Web use as well? 
I tried is basically, and nothing happens with either `InAppBrowser.openWebView` or `InAppBrowser.open`

If not, can you make it clear in the docs that for web we need to stick with something else?
If so, are there any web caveats?

EG: we tried `@capacitor/browser` which is really VERY limited, and also does not seem to work great on iOS Safari browsers (for PWA or Browser based apps)  Then switching to this we hoped to get better handling of `window.open` in a browser but it seems not, and I cannot find and specifics in the docs for it? (maybe I'm just missing something?)

**Comment by riderx** [comment]
Web is not supported, and there no really way to do better than `window.open` sadly

**Comment by riderx** [comment]
i added to the doc
