### ISSUE TITLE
 addListener urlChangeEvent listener is not working 

### ISSUE THREAD

**Issue by arunchinna04** [Cap-go/capacitor-inappbrowser#111]
I'm encountering an issue where i need to listen to URL changes occurring after the webview is loaded, but the addListener urlChangeEvent doesn't seem to be executing. Despite implementing the listener, it doesn't respond to URL changes. Could you please provide guidance or suggest alternative approaches to effectively capture these URL changes ? 

await InAppBrowser.open({ url: 'https://capgo.app' })

//Below code is working even the url gets changed
InAppBrowser.addListener("urlChangeEvent", (e: any) => {
      console.log('event', e.url);
 })

**Comment by riderx** [comment]
No, open use the native webview and so this cannot be implemented
