### ISSUE TITLE
Fileselector not working with openWebView

### ISSUE THREAD

**Issue by waberger** [Cap-go/capacitor-inappbrowser#113]
Seems like the input type="file" does nothing if clicking on it inside an webview. I tried to modify the plugin like this: https://stackoverflow.com/questions/70132381/how-to-upload-file-through-android-webview-app but it's still not working. Is there an fix for this?. Same issue for file downloads but that's something i have fixed.

**Comment by karen1au** [comment]
Having the same issue, it's only happening on Android for me
