### ISSUE TITLE
Webview and Ionic Communication

### ISSUE THREAD

**Issue by jeanpfs** [Cap-go/capacitor-inappbrowser#114]
Hello, is there any way to capture a message from the webview?

In React Native, I can do something like the code below, but I couldn't find a solution for this in your library.

```
const INJECTED_JAVASCRIPT = `(function() {
    window.ReactNativeWebView.postMessage(JSON.stringify({key : "value"}));
})();`;



<WebView
  source={{ uri: 'https://reactnative.dev' }}
  injectedJavaScript={INJECTED_JAVASCRIPT}
  onMessage={(event) => {
       const data = JSON.parse(event.nativeEvent.data);
       alert(data.key);
  }}
/>;

```

**Comment by korenskoy** [comment]
Hi.
This plugin doesn't know how to work with `postMessage`.
Here is a similar issue https://github.com/Cap-go/capacitor-inappbrowser/issues/84

**Comment by riderx** [comment]
This could be done pretty fast. You can support it here: https://console.algora.io/bounties/new

**Comment by xam8re** [comment]
A workaround that I developed in cordova webview was reading local storage.  Now I preferred using directly a websocket (using pusher)

**Comment by riderx** [comment]
Hello, I needed the feature for my last project, so I made it.
You can now post messages from inappbrowser like that: 
```js
window.mobileApp.postMessage({ "detail": { "message": "myMessage" } })
```
And listen to it from the Capacitor webview with 
```js
InAppBrowser.addListener('messageFromWebview', (event) => {
  console.log('messageFromWebview', event)
})
```
Both ways were implemented.
To do the reverse from Capacitor webview
```js
    InAppBrowser.postMessage({
      detail: {
        status: 'ok4',
      },
    })
```
And listen in the inappbrowser:
```js
  window.addEventListener('messageFromNative', (event: CustomEvent) => {
    const message = event.detail
    console.log('Received message from native:', message)
    // Handle the message here
    // For example, you could update some state or trigger an action
  })
```

**Comment by johannesress** [comment]
We also have the issue, that "window.mobileApp" is undefined in Android - it works fine for iOS. 

Is there any way to solve this - we need this to work in iOS and Android.

**Comment by frasza** [comment]
I have actually updated from 7.10.0 to 7.10.5 and now it is always undefined.

**Comment by riderx** [comment]
How correct I was doing refactor to remove some ARN issue on android.
It should be good now on` 7.10.7` please try it

**Comment by frasza** [comment]
@riderx thank you so much for quick response and active, appreciate it.
Unfortunately so far, I haven't been able to make it work. In the page I am opening with `InAppBrowser.openWebView` I have script where I do `if (window.mobileApp` and it is still undefined when I check it. :(

**Comment by riderx** [comment]
can you share how you test ?

**Comment by frasza** [comment]
Unfortunately its work code, but in general I have a page where I have some buttons where on click I want to send a message back. I open that page with `await InAppBrowser.openWebView({
      url,
      visibleTitle: false
    })` and on page I have tried to display `window.mobileApp` with example of span text like `document.getElementById("test").innerHTML=window.mobileApp` -- it shows `undefined`. Also on callback called when button is clicked I have `if (window.mobileApp)` which is skipped.
