### ISSUE TITLE
urlChangeEvent call is not working on Android

### ISSUE THREAD

**Issue by JoseManuelGdlO** [Cap-go/capacitor-inappbrowser#127]
I'm trying to use the plugin using this listener but it doesn't work, it doesn't enter and doesn't seem to be doing anything, it creates the browser but doesn't enter the event.

**Comment by ha-akelius** [comment]
I have the same issue,
but it worked for me with `InAppBrowser.openWebView`

**Comment by riderx** [comment]
it works only in openWebView we cannot do it for the other one
