### ISSUE TITLE
Possible to open inapp browser hidden mode

### ISSUE THREAD

**Issue by YanouonaY** [Cap-go/capacitor-inappbrowser#133]
Hello,

Is it possible to open inapp with url in hidden mode?

usecase: if you want to execute a logout URL with token

Thanks

**Comment by avioli** [comment]
@YanouonaY I would second that - I strongly suggest you make a `window.fetch` request instead of opening an in-app browser in a "hidden" mode.

**Comment by YanouonaY** [comment]
Thnaks, but my test with fetch open one browser....

**Comment by avioli** [comment]
Can you show some code @YanouonaY?

Are we talking about the same [window.fetch()](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)?

This API doesn't open browsers - it makes a request and you may handle the response (or ignore it, if it's what you want). The only way I see `window.fetch()` opening a browser window is if you or a some code replaces it with something that does open a browser!

**Comment by YanouonaY** [comment]
fetch is ok
