### ISSUE TITLE
Translation Error With Android

### ISSUE THREAD

**Issue by gasci** [Cap-go/capacitor-inappbrowser#145]
Thank you for this great plugin and active maintenance.

I am getting this error when I try to translate a page via the plugin.

<img width="319" alt="Screenshot 2024-06-12 at 10 45 01" src="https://github.com/Cap-go/capacitor-inappbrowser/assets/29505701/244ba86a-0acf-417a-aac4-25eb5d6704ad">

The problem is visible only with Android, iOS system tool are able to translate this page.

What can be the reason for this error?

**Comment by riderx** [comment]
Thanks for the feedback did you tried to inspect it to see any error in the console ?

**Comment by gasci** [comment]
I am afraid that it fails without an error.

![Screenshot 2024-06-14 at 09 52 28](https://github.com/Cap-go/capacitor-inappbrowser/assets/29505701/ac271738-1af7-40e1-8bd3-4a71ab3691ef)

**Comment by riderx** [comment]
You are inspecting the app, you need to inspect the plugin browser.
And make sure you made it inspectable

**Comment by gasci** [comment]
Oops. You are right. We are having a different error here:
![Screenshot 2024-06-14 at 19 58 56](https://github.com/Cap-go/capacitor-inappbrowser/assets/29505701/80a2e2b8-242b-42ee-bcd4-b8263c783008)

How can I make the logs more visible for you?

**Comment by riderx** [comment]
The bug is not linked to the plugin, it's more an issue on IOS i think then

**Comment by gasci** [comment]
I confirm that starting from v6.0.24 translations on Android work well. Thank you @riderx
