### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by mariusbolik** [Cap-go/capacitor-inappbrowser#15]
Hi, thank you for the great plugin!

Could you please tell me what's the difference between `open()` and `openWebView()`?
And what does `isPresentAfterPageLoad` do?

I would appreciate it if you could add a description to every method and every option to the readme. This could increase the adoption rate of the plugin :)

Last thing: Wouldn't it be necessary to provide a `removeActionHandler()` method to avoid memory leaks?

Best Regards,
Marius

**Comment by riderx** [comment]
Sorry for the delay i didn't saw it in my notif, i add removeActionHandler now and update the README

**Comment by riderx** [comment]
Should be good now in `0.4.0` sorry for the delay

**Comment by bhekor** [comment]
I agree sample usage and explanation
