### ISSUE TITLE
[Feature Request] Browser error passing

### ISSUE THREAD

**Issue by theNomik** [Cap-go/capacitor-inappbrowser#160]
Use case: 

After opening webView browser window via `browser.openWebView({ url, toolbarType: ToolBarType.BLANK, visibleTitle: false });` I want to be able to catch/listen for specific errors throwed by Android/iOS browsers _for example_ `ERR_NAME_NOT_RESOLVED`, `ERR_ADDRESS_UNREACHABLE`, `ERR_TIMED_OUT`... for Android or `NSURLErrorTimedOut`, `NSURLErrorUnknown`, `The Internet connection appears to be offline.`... for iOS.

On javascript side `browser.addListener('pageLoadError', (errorContext) => { console.log(errorContext) }` is already listenable, even thro lib itself does not oficially provide `pageLoadError` listener, but error source (`errorContext`) is not visible/defined.

https://developer.apple.com/documentation/foundation/1508628-url_loading_system_error_codes
https://github.com/chromium/chromium/blob/main/net/base/net_error_list.h

Edit: Actually we use [v1.4.4](https://www.npmjs.com/package/@capgo/inappbrowser/v/1.4.4) of `@capgo/inappbrowser`

**Comment by WcaleNieWolny** [comment]
Please attempt [this method](https://github.com/Cap-go/capacitor-inappbrowser/issues/114#issuecomment-2319973299)
