### ISSUE TITLE
multiple file upload

### ISSUE THREAD

**Issue by xam8re** [Cap-go/capacitor-inappbrowser#168]
Hi.
There is a way to enable multiple file upload? 
I have a form that suport multiple file but on android, file chooser offer only single file.

**Comment by riderx** [comment]
You can try in `6.5.0`

**Comment by xam8re** [comment]
Still not present on npm packages

**Comment by riderx** [comment]
Sorry lint issue check now

**Comment by xam8re** [comment]
Present now. You can close this MR. thanks
