### ISSUE TITLE
Question urlChangeEvent

### ISSUE THREAD

**Issue by nseb** [Cap-go/capacitor-inappbrowser#19]
Hello , we use inappbrowser cordova for intercept loadstart 
`ref.on('loadstart').subscribe(myCallback); `

urlchangeEvent works same ?

You use capacitor properties android."overrideUserAgent" and ios."overrideUserAgent" for override agent version ?

**Comment by riderx** [comment]
urlchangeEvent is made to detect when the url change, like user click on link and that change the URL, for what do you use loadstart event ?

**Comment by UTSOURCE** [comment]
It can be used for interception, such as modifying the address during access

**Comment by nseb** [comment]
For me , I detect redirect on universal link on my app (example during oauth) , to close get url , close the inappbrowser and push th url directly in app.

**Comment by riderx** [comment]
So yes you can use the plugin for that, that the exact usecase i built it
