### ISSUE TITLE
feat: Add close event

### ISSUE THREAD

**Issue by mariusbolik** [Cap-go/capacitor-inappbrowser#20]
Hello @riderx,

could you add an event listener that fires when a user closes the browser by clicking on the "Finish" button?

Regards,
Marius

**Comment by riderx** [comment]
Hey Marius,
i believe it's doable let me check

**Comment by riderx** [comment]
i let you try the version 0.4.0

**Comment by OskarLebuda** [comment]
@riderx  can you share `0.4.0` for me as well?

**Comment by riderx** [comment]
it's public, you can check with npm

**Comment by riderx** [comment]
Sorry, the auto-release script was broken. I fix now, try to download the `0.4.0`
