### ISSUE TITLE
bug: executeScript doesn't work in iOS WebView

### ISSUE THREAD

**Issue by thibaut129** [Cap-go/capacitor-inappbrowser#234]
### Version

6.9.13

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

Hi,
I'm a new user of this wonderful plugin but I have an issue. 
I encountered an issue where the executeScript method does not work as expected. When trying to execute a script in the InAppBrowser’s WebView, nothing happens.
The script does not execute, and no error is logged.

### Expected behavior

The executeScript method should inject the provided script (alert('Hello from the website!');) into the WebView and execute it.

### Steps to reproduce

```
async openWebsite() {
  await InAppBrowser.openWebView({
    url: 'https://www.google.fr/'
  });

  await InAppBrowser.addListener('urlChangeEvent', (data) => {
    console.log('URL changed:', data.url);
    // alert('URL changed:' + data.url);
  });

  await InAppBrowser.executeScript({
    code: `alert('Hello from the website!');`
  });
}
```

### Other information

I test it on an Xcode iOs Simulator : 
Here the output : 
⚡️  To Native ->  InAppBrowser openWebView 655573
⚡️  TO JS undefined
⚡️  TO JS {"url":"https:\/\/www.google.fr\/"}
⚡️  TO JS {"url":"https:\/\/www.google.fr\/"}
⚡️  TO JS {"url":"https:\/\/www.google.fr\/"}
⚡️  TO JS {"url":"https:\/\/www.google.fr\/"}
⚡️  To Native ->  InAppBrowser addListener 655574
⚡️  To Native ->  InAppBrowser executeScript 655575
⚡️  TO JS undefined
⚡️  [log] - URL changed: https://www.google.fr/
⚡️  TO JS undefined

### Capacitor doctor

[warn] The bundledWebRuntime configuration option has been deprecated. Can be
       safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

[info] Using Gemfile: RubyGems bundle installed
[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

### Fastest way to fix this issue

- [ ] I want to get this fix ASAP and [found the issue with Algora](https://console.algora.io/org/gl/bounties/community?fund=Cap-go%2Fcapacitor-inappbrowser) we recommend ($50 to $500)

**Comment by thibaut129** [comment]
Working on android with simulator

**Comment by thibaut129** [comment]
Hi @riderx  and @WcaleNieWolny ,

For information I try with several iOS version with the simulator (18,17,16) and I don't have result with any of this....
In android I don't have this problem....

This afternoon I will try with a real iPad and perhaps I will downgrade the capacitor plugin....

Thanks for your help

**Comment by WcaleNieWolny** [comment]
@thibaut129 this is not a problem with executeScript, but rather with `alert`. Alert will not work in the iOS webview by default. If you did `console.log` instead of alert, the script would execute properly.

I also believe that you may be using `executeScript` in a wrong way.
You should NOT be using `executeScript` to insert a script that runs immediately after the page load.

Instead, you should do the following:
1. Set `isPresentAfterPageLoad` when calling `openWebView`
2. Set a `preShowScript`. In you case`, the script would look something like this:
```ts
InAppBrowser.openWebView({ 
  url: 'https://www.google.fr/',
  isPresentAfterPageLoad: true,
  preShowScript: 'console.log("hello!!");'
})
```

**Comment by thibaut129** [comment]
Hi @WcaleNieWolny ,
Thanks for your answer

I confirm I put alert just for debug but with console log I have the same behaviour.
Here my update code

```typescript
await InAppBrowser.openWebView({
  url: 'https://www.google.fr/',
  isPresentAfterPageLoad: true,
  preShowScript: 'console.log("Hello from the webview after render !!");'
});

await InAppBrowser.addListener('urlChangeEvent', (data) => {
  console.log('URL changed  :', data.url);
  // alert('URL changed:' + data.url);
});

await InAppBrowser.executeScript({
  code: '(console.log("Hello from the webview before render !!");'
});
```
  


With update Result : 
⚡️  To Native ->  InAppBrowser openWebView 6575591
⚡️  To Native ->  InAppBrowser addListener 6575592
⚡️  To Native ->  InAppBrowser executeScript 6575593
⚡️  TO JS undefined
⚡️  TO JS undefined
⚡️  TO JS {"url":"https:\/\/www.google.fr\/"}
⚡️  TO JS {"url":"https:\/\/www.google.fr\/"}
⚡️  TO JS {"url":"https:\/\/www.google.fr\/"}
⚡️  [log] - URL changed  : https://www.google.fr/
⚡️  [log] - URL changed  : https://www.google.fr/
⚡️  [log] - URL changed  : https://www.google.fr/
[InAppBrowser - InjectPreShowScript] PreShowScript script: async function preShowFunction() {
console.log("Hello from the webview after render !!");
};
preShowFunction().then(
        () => window.webkit.messageHandlers.preShowScriptSuccess.postMessage({})
).catch(
        err => {
                console.error('Preshow error', err);
                window.webkit.messageHandlers.preShowScriptError.postMessage(JSON.stringify(err, Object.getOwnPropertyNames(err)));
        }
)
⚡️  TO JS undefined


If you want more detail tell me

**Comment by WcaleNieWolny** [comment]
I really don't understand how you reached the conclusion that `preShowScript` is not working. You CANNOT see the logs from the inappbrowser in the xcode logs, this is to be expected.

Please open the developer's tools via safari -> develop -> your device (np: ipad, simulator etc) -> google.fr

**Comment by thibaut129** [comment]
this ? :
![image](https://github.com/user-attachments/assets/5a7a9537-69bb-4529-b285-503f019f758e)

**Comment by WcaleNieWolny** [comment]
No, the other one. (The tools for google.fr, not for your capacitor app)

**Comment by thibaut129** [comment]
Ok perfect ! Sorry for miscomprehension. So the solution is to pass through  preShowScript ! 
And alert works on iOs ! Thanks a lot

**Comment by thibaut129** [comment]
Ok perfect ! Sorry for miscomprehension. So the solution is to pass through  preShowScript ! 
And alert works on iOs ! Thanks a lot
