### ISSUE TITLE
How to use plugin

### ISSUE THREAD

**Issue by DidoMarchet** [Cap-go/capacitor-inappbrowser#31]
Hi guys,
sorry for the dummy question but I'm asking you how to use the plugin.
I installed it, I've sync capacitor and after?
I must import browser from the plugin ot I still use the capacitor browser?

Really thanks and kind regards,

Davide

**Comment by DidoMarchet** [comment]
Hi @riderx thanks for reply!

i still have an error :(

It returns:
`Uncaught (in promise) SyntaxError: The requested module '/node_modules/.vite/deps/@capgo_inappbrowser.js?v=c0eea13c' does not provide an export named 'CapacitorInappbrowser' `

I installed `"@capgo/inappbrowser": "^0.4.7"` with pinic core 7 and capacitor 4 and Vue 3.

If you can help me i'm really really glad because the functionality of this plugin is awesome.

Thanks and kind regards,

Davide

**Comment by riderx** [comment]
@DidoMarchet sorry i missleaded you. it's `InAppBrowser` instead of `CapacitorInappbrowser`

**Comment by DidoMarchet** [comment]
hi @riderx ,
the correct is `import { InAppBrowser } from "@capgo/inappbrowser";` and it works like a charm!
Really thanks!

**Comment by riderx** [comment]
Thanks for the report, i added it to the readme as well !
