### ISSUE TITLE
openWebView() crashes on Android

### ISSUE THREAD

**Issue by cyrilfr** [Cap-go/capacitor-inappbrowser#43]
I tried to use openWebView() in my app on Android but it crashes. This seems to be related to the theme I use in my AndroidManifest.xml.

It throws an exception:

    java.lang.ClassCastException: androidx.appcompat.widget.Toolbar cannot be cast to android.widget.Toolbar

I fixed this issue by simply replacing the `import` in the source code of this plugin.

**Comment by riderx** [comment]
do you use capacitor 5 or 4 ?

**Comment by cyrilfr** [comment]
I'm using Capacitor 5.

**Comment by riderx** [comment]
Ok i think i found the issue can you try again ?

**Comment by bhekor** [comment]
If you can help others with your resolve, it'll be great. thanks.

**Comment by riderx** [comment]
@bhekor not sure to understand heat you mean it’s working on latest version I fixed it
