### ISSUE TITLE
Remove toolbar and toolbar options (Menu)

### ISSUE THREAD

**Issue by bhekor** [Cap-go/capacitor-inappbrowser#54]
On the web browser, there is a share icon and menu that's having options including opening with Chrome I want to get rid of them.

just having only the close or back button left.

**Comment by riderx** [comment]
You have 2 way to open the browser one is fully configurable with button you want in it.
https://github.com/Cap-go/capacitor-inappbrowser#openwebview
check the options there:
https://github.com/Cap-go/capacitor-inappbrowser#openwebviewoptions
