### ISSUE TITLE
Clear cache and session

### ISSUE THREAD

**Issue by asieverding** [Cap-go/capacitor-inappbrowser#67]
Hey there :)
Is there an option to clear browser cache and session? I would like to use the in app browser to process an OAuth login with Microsoft services, but after a logout I need to clear cache and session. Otherwise the OAuth flow authenticates the same user account without login with mail and password the next time the in app browser is opened.

**Comment by asieverding** [comment]
Some options like clearcache or clearsessioncache for example. Like in the https://www.npmjs.com/package/cordova-plugin-inappbrowser plugin.

**Comment by riderx** [comment]
Hello thanks for the report, if you are willing to support the project someone from the community can make it for you:
https://github.com/sponsors/riderx

**Comment by jessmathews** [comment]
hey @riderx has this issue been solved? 
do I need to add to the readme after adding the clearcache or clearsessioncache functionality?

**Comment by riderx** [comment]
Thanks for solving this, the readme is auto update when you update the TS file, just run the build command.
Please also run the lint and verify to be sure all build

**Comment by jessmathews** [comment]
I ran 
```bash
npm run lint
npm run build 
npm run verify:web && npm run verify:android
```

The only errors were `/home/user/capacitor-inappbrowser/src/definitions.ts
  0:0  error  Parsing error: DeprecationError: 'originalKeywordKind' has been deprecated since v5.0.0 and can no longer be used. Use 'identifierToKeywordKind(identifier)' instead
`
Everything else worked fine.

**Comment by asieverding** [comment]
any updates?

**Comment by riderx** [comment]
This has been merged and fixed ! sorry for the delay

**Comment by asieverding** [comment]
Can someone provide an example how to use it correctly?
I want to clear the cache of the in app browser completly. The new feature is bound to the clearCookies function and requires an url but even if I enter a url and set the cache option to true, the cache is not deleted.
