### ISSUE TITLE
Customize the top bar color/text/close button

### ISSUE THREAD

**Issue by AsimDawrat** [Cap-go/capacitor-inappbrowser#70]
Is there a way to customize the top bar color/text/close button for web view?

I need to do following things from the top bar:
1. Hide the website name
2. Change the background color of top bar
3. Change the close icon from "X" to ">"

Please help how can I achieve it?

**Comment by riderx** [comment]
This is not actually doable, if you need it you can support the project and i will create a bounty to make it done by someone of the community

**Comment by riderx** [comment]
So to be clear, the goal here is to add option in the plugin to allow hide/show title, in both method open and openwebview.
And allow to change the icon with a setting like CloseIcon: 'X' : '>'

**Comment by PrabhbirJ** [comment]
> So to be clear, the goal here is to add option in the plugin to allow hide/show title, in both method open and openwebview. And allow to change the icon with a setting like CloseIcon: 'X' : '>'
Only openwebview method is having code for handling titlebars and other things. I don’t think open method provides this functionality. Also I checked last commits for reload button they were also implemented in the openwebview only. Let me know more. Thank you
