### ISSUE TITLE
Update the CONTRIBUTING.md

### ISSUE THREAD

**Issue by RANJEETJ06** [Cap-go/capacitor-inappbrowser#82]
the files are outdated and will be difficult to understand code base

**Comment by riderx** [comment]
Sorry i'm not sure what you mean ?

**Comment by RANJEETJ06** [comment]
as some one new come to your code base at first he/she need to understand the code base 

which file should i follow ?

**Comment by riderx** [comment]
Mmm okay i think the capacitor doc on how plugin work would help :
https://capacitorjs.com/docs/plugins/creating-plugins

**Comment by RANJEETJ06** [comment]
got it
