### ISSUE TITLE
InAppBrowser.close() closes the entire application instead of just the WebView

### ISSUE THREAD

**Issue by Senzo13** [Cap-go/capacitor-inappbrowser#87]
I am currently using the capacitor-inappbrowser plugin to open URLs within a WebView in my application. While the InAppBrowser.openWebView() method works as expected and opens the URL correctly, I am encountering an issue when trying to close the WebView.

**Steps to reproduce:**

Use InAppBrowser.openWebView() to open a URL.
Add a listener for the urlChangeEvent to capture URL changes.
Once the URL change event is captured, use InAppBrowser.close() to close the WebView.
Expected Behavior:
The WebView should close, and the user should return to the main application.

**Actual Behavior:**
The entire application closes instead of just the WebView.

**Additional Information:**

The listener for the urlChangeEvent correctly captures the event and the URL.
The issue persists across multiple attempts and seems consistent.
```
Framework : Angular 16 / Ionic 7.4
Platform : Android
Simulator : PIxel 6a API 33
```
I would appreciate any guidance or fixes for this issue. Thank you!

**Comment by mohanmuthusamy** [comment]
I am getting the same issue above. Does anyone help with this?

**Comment by slavsobuzz** [comment]
Hello, I encounter the same error which is very blocking in the progress of the development of my application. Hoping that someone has managed to resolve this issue.

Best regards.

**Comment by Senzo13** [comment]
I fixed the problem temporarily this way

When using the close method of the InAppBrowser plugin, instead of just closing the WebView, the entire activity is being closed. This behavior is observed when the line notifyListeners("closeEvent", new JSObject().put("url", webViewDialog.getUrl())); is active. Commenting out this line seems to resolve the issue.

Theory:

It's possible that the "closeEvent" is being handled in a specific way on the JavaScript side that triggers the activity to close. When the event is emitted by notifyListeners, the event handler on the JavaScript side might be executing some code that results in the activity closing or other unintended behaviors.

Recommendation:

Check how the "closeEvent" is being handled in your JavaScript code. Ensure no code is closing the activity or causing unintended behavior.
If the JavaScript event handler is in order, there might be an issue with how Capacitor handles events between native code and JavaScript. In this case, further investigation would be needed.

Commented line to temporarily resolve the issue
![image](https://github.com/Cap-go/capacitor-inappbrowser/assets/52446531/5ab4da11-a7df-44e4-8094-414100153422)

If the creator of capgo agrees, I can offer my npm package temporarily

**Comment by mohanmuthusamy** [comment]
@Senzo13 You are doing a great job! It worked after I commented on the line you highlighted earlier.

**Comment by mohanmuthusamy** [comment]
@Senzo13 I closed the web view, and it routed to another page via code( this.router.navigate), but it did not redirect to another page. It still stays the same. Is there any reason?

**Comment by Senzo13** [comment]
When the webVIew closes, and you try to navigate it takes you back to the weVIew which was closed? What technology do you use? I'm on Angular with Ionic

**Comment by mohanmuthusamy** [comment]
@Senzo13 I'm also using Ionic angular, and this is my code 
<img width="678" alt="image" src="https://github.com/Cap-go/capacitor-inappbrowser/assets/6388228/ce6e2dff-87cf-4ca2-88e6-41113b07752f">

**Comment by riderx** [comment]
Hello guys sorry for the issue, it was not closing the app but crashing it, the close event needed to read the current url and that has to be in the main thread.
please try the 1.2.13 it should be fixed, sorry for this
