### ISSUE TITLE
Dispose WebView after closing

### ISSUE THREAD

**Issue by c01nd01r** [Cap-go/capacitor-inappbrowser#94]
Hello!
I noticed that WebView in Android is not being destroyed after it's closed. As far as I can see in the plugin code (I'm not an Android developer), there is no explicit call to the webView.destroy() method anywhere.

Is this the correct behavior? Should it be fixed, even though it might break backward compatibility in some cases?
I recorded my observation on video.

<details>
<summary>screen recording</summary>

https://github.com/Cap-go/capacitor-inappbrowser/assets/3511312/7c96f625-119a-4f0a-aefa-2712f427ff7a

</details>

**Comment by riderx** [comment]
Can you open a Pr with your change?

**Comment by riderx** [comment]
i added it already after you report and forgot to tell you thanks for the report

**Comment by c01nd01r** [comment]
> i added it already after you report and forgot to tell you thanks for the report

Awesome! Thank you so much 🤝
