### ISSUE TITLE
Following deep links in WebViewDialog

### ISSUE THREAD

**Issue by eljass** [Cap-go/capacitor-inappbrowser#98]
Currently if inside the webview links redirects to the deeplinked addresses the page does not load because URL is invalid (URL schema is not `http://` or `https://`). So we are experiencing this sort of issues:

![image (7)](https://github.com/Cap-go/capacitor-inappbrowser/assets/7661970/8027e4dc-cf61-4da3-b4f9-217cb86a3e9c)

Would it be possible to adjust WebView configs to open external application in these cases rather than trying to load the URL inside the WebView itself?

I assume the fix lies inside these lines:
https://github.com/Cap-go/capacitor-inappbrowser/blob/f7962d27b2a7acc5ba9827d969f61abe7857af32/android/src/main/java/ee/forgr/capacitor_inappbrowser/WebViewDialog.java#L314C1-L321C1

So instead of this:
```java
@Override
public boolean shouldOverrideUrlLoading(
  WebView view,
  WebResourceRequest request
) {
  return false;
}
```

function could look something like this:

```java
@Override
public boolean shouldOverrideUrlLoading(
  WebView view,
  WebResourceRequest request
) {
  Context context = view.getContext();
  String url = request.getUrl().toString();

  if (!url.startsWith("https://") && !url.startsWith("http://")) {
    Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

    context.startActivity(intent);
    return true;
  }

  return false;
}
```

Does this make sense?

**Comment by riderx** [comment]
It does did you tried your fix?
if yes please open a PR and i merge it

**Comment by eljass** [comment]
Not yet, can do so soon though. For now we had another possible workaround for it with [capacitor's app-launcher plugin](https://capacitorjs.com/docs/apis/app-launcher). In this workaround we attach listener for urlChanged event in here and if the schema is something else than `http` or `https` we try to open another app with that URL by:

1. Attach listener: `addListener("urlChangeEvent", handleUrlChange)`
2. Inside `handleUrlChange`, check if URL can be opened: [canOpenUrl(options: CanOpenURLOptions) => Promise<CanOpenURLResult>](https://capacitorjs.com/docs/apis/app-launcher#canopenurl)
3. And then open URL in another app if possible: [openUrl(options: OpenURLOptions) => Promise<OpenURLResult>](https://capacitorjs.com/docs/apis/app-launcher#openurl)

Although might be good to attach this deepLink handler directly into this plugin so I'll try that!

**Comment by riderx** [comment]
Thanks it's merged
